/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatcat;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.UnsupportedEncodingException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.InvalidKeyException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.security.MessageDigest ;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;


/**
 *
 * @author konch
 */
public class ChatCat11 extends javax.swing.JFrame {
    
    private static int SERVERPORT = 5455;
    static boolean AUTH=false;
    /**
     * Creates new form NewJFrame
     */
    public ChatCat11() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ChatCat");

        jInternalFrame1.setVisible(true);

        jLabel2.setText("Login");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("SEND");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear Chat");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Disconnect and Quit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton5.setText("Chat");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton4)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //LOGIN BUTTON
        
        InetAddress host = null;
        Socket link = null;
        String username = jTextField1.getText();
        username=username.trim();
        String password = jPasswordField1.getText();
        password = password.trim();
        
        MyUser = username;
        
        System.out.print(username+" + "+password );
        
        MessageObject mo=null;
        try {
            mo = new MessageObject(username,password,MYPORT);
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try
        {
            host = InetAddress.getLocalHost();
        }
        catch(UnknownHostException uhEx)
        {
            System.out.println("Host ID not found!");
            System.exit(1);
        }
        
        System.out.println(mo.username+" + "+mo.hashpasswd );
        try {
            link = new Socket(host,SERVERPORT);
            
            ObjectOutputStream oos;
            oos = new ObjectOutputStream(link.getOutputStream());
            oos.writeObject(mo);
            link.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int i=0;
        do
        {
            System.out.println(AUTH+" is still");
            if (AUTH==true)
            {
                System.out.println(AUTH);
                
                jInternalFrame1.hide();
                jButton2.setEnabled(true);
                jTextField2.setEnabled(true);
                jButton3.setEnabled(true);
                jButton5.setEnabled(true);
                jTextField3.setEnabled(true);
                
                
                MyUser = mo.username;
                jLabel1.setText("ChatCat : "+MyUser.toUpperCase());
                
                break;
            }
            else if (i==2000) 
            {
                jLabel2.setText("Login Failed");
                break;
            }
            try {
                Thread.sleep(2);
                i++;
            } catch (InterruptedException ex) {
                Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
            }
            }while(true);
        
        System.out.println("Connection Successful");
        
//        try
//        {
//            //System.out.println("\n* Closing connection... *");
//            //link.close(); //Step 4.
//        }
//        catch(IOException ioEx)
//        {
//            System.out.println(
//                    "Unable to disconnect!");
//            System.exit(1);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //SEND BUTTON
        
        if (canChat)
        {
            String textchat = jTextField2.getText();
            textchat=textchat+"\n";
            jTextField2.setText("");
            jTextArea1.append("Me:> "+textchat);
            
            ////
            //Encryption of Text
            
            String etext = MessageObject.EncryptMessage(textchat);
            
            ///Checksum
            
            long chksum = MessageObject.getCheckSumCRC32(etext);
            
            ////
            MessageObject mo = new MessageObject(MyUser,etext,TOPORT,2);
            
            mo.checksumval = chksum;
            
            Socket link;
            link = null;
        
            System.out.println("Sending message to "+jTextField3.getText());
        try {
            link = new Socket(InetAddress.getLocalHost(),TOPORT);
            
            ObjectOutputStream oos;
            oos = new ObjectOutputStream(link.getOutputStream());
            oos.writeObject(mo);
            link.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea1.append("Message Could not sent as other client disconnected");
        }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        MessageObject mo=null;
        InetAddress host=null;
        //MessageObject mo=null;
        try {
            mo = new MessageObject(MyUser,"",MYPORT);
            mo.flag=-1;
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try
        {
            host = InetAddress.getLocalHost();
        }
        catch(UnknownHostException uhEx)
        {
            System.out.println("Host ID not found!");
            System.exit(1);
        }
        
        Socket link;
        link = null;
        
        try {
            link = new Socket(host,SERVERPORT);
            
            ObjectOutputStream oos;
            oos = new ObjectOutputStream(link.getOutputStream());
            oos.writeObject(mo);
            link.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
        System.exit(0);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        InetAddress host = null;
        //CHAT BUTTON
        
        String username = jTextField3.getText();
        String password = null;
        System.out.print(username+" + "+password );
        
        MessageObject mo=null;
        try {
            mo = new MessageObject(username,"",MYPORT);
            mo.flag=1;
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try
        {
            host = InetAddress.getLocalHost();
        }
        catch(UnknownHostException uhEx)
        {
            System.out.println("Host ID not found!");
            System.exit(1);
        }
        
        Socket link;
        link = null;
        
        System.out.println(mo.username+" + "+mo.hashpasswd );
        try {
            link = new Socket(host,SERVERPORT);
            
            ObjectOutputStream oos;
            oos = new ObjectOutputStream(link.getOutputStream());
            oos.writeObject(mo);
            link.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    static int MYPORT = 1226;
    static int TOPORT = 1225;
    //static int MYPORT,TOPORT;
    
    
    
    static boolean canChat = false;
    static String MyUser = null;
    //private final String KEYSTRING = "Kq&#9Id82d0S6$h8";
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatCat11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatCat11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatCat11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatCat11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChatCat1().setVisible(true);
                
                ChatCat11 cc = new ChatCat11();
                //String clientname = args[2];
                String clientname = "<CLIENT-2>";
                cc.setTitle("ChatCat"+clientname);
                cc.setVisible(true);
                //MYPORT = Integer.parseInt(args[0]);
                //TOPORT = Integer.parseInt(args[1]);
                System.out.println(clientname+">> "+MYPORT+" "+TOPORT);
                //cc.jLabel2.setText("HAHAHAHHAHA");
                
                
                Thread t = new Thread()
                {
                  	public void run()
        {
            
        try
	{
		//new ChatCat1().setVisible(true);
		
		
                Socket link = null;
		System.out.println(clientname+">> Opening port...\n");
		
		ServerSocket servSock;
		servSock = new ServerSocket(MYPORT);
		
		while (true){
			System.out.println(clientname+">> Waiting for Requests");
			link = servSock.accept(); //Step 2.
			//Scanner input = new Scanner(link.getInputStream());//Step 3.
			ObjectInputStream ois = new ObjectInputStream(link.getInputStream());
			InetAddress cli = link.getLocalAddress();
                        
                        MessageObject mo =  (MessageObject)ois.readObject();
                        System.out.println(clientname+">> Flag value: "+mo.flag);
                        if (mo.flag == 1)
                        {
                            System.out.println(clientname+">> DONE!!!");
                            AUTH=true;
                            //jInternalFrame1.hide();
                            
                        }
                        else if (mo.flag == 2)
                        {
                            
                            canChat = true;
                            cc.jTextField3.setEnabled(false);
                            System.out.println(clientname+">> Got it at 2");
                            System.out.println(mo.message);
                            
                            if (mo.message!=null )
                            {
                                long checksumval = MessageObject.getCheckSumCRC32(mo.message);
                                if (checksumval == mo.checksumval)
                                {
//                                String textchat = cc.jTextField2.getText();
//                                textchat="Me:> "+textchat+"\n";
//                                //cc.jTextField2.setText("");
//                                cc.jTextArea1.append(textchat);
                                
                                String dtext = MessageObject.DecryptMessage(mo.message);
                                String textchat = cc.jTextArea1.getText();
                                System.out.println(clientname+">> Decrypted message: "+dtext);
                                System.out.println(clientname+">> Current Text : "+textchat);
                                textchat = textchat+ mo.username+":> "+ dtext+"\n";
                                cc.jTextArea1.setText(textchat);
                                //cc.jTextArea1.append("\n");
                                }
                            }
                            
                            
                        }
        }
	}       catch (IOException ex) {
		Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
	}                     catch (ClassNotFoundException ex) {
                                  Logger.getLogger(ChatCat11.class.getName()).log(Level.SEVERE, null, ex);
                              }
	}  
                };
                
                t.start();
                
            }
            
            
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
